package tercero.com.base.models;

public enum RolArtistaEnum {
    SOLISTA, VOCALISTA, GUITARRISTA, BAJISTA, BATERISTA, SAXOFONISTA, TRUMPETISTA, PERCUSIONISTA, VIOLINISTA, FLAUTISTA, CANTANTE, COMPOSITOR, PRODUCTOR;
}
